from pathlib import Path

from omx_remote.runtime.agents.codex_agent_materialization_plan import (
    build_codex_agent_materialization_plan,
)
from omx_remote.schemas.agents.codex_agent_materialization_schemas import (
    CodexAgentMaterializationTarget,
)


def _write_agent_config(root: Path) -> None:
    (root / ".agent-remote.toml").write_text(
        """
[agents.architect]
enabled = true
provider = "codex"
role = "architect"
model = "gpt-5.5"
effort = "high"
persona = "Design typed boundaries."
routing_hints = ["architecture", "contracts"]

[agents.reviewer]
enabled = false
provider = "codex"
role = "reviewer"
model = "gpt-5.5"
effort = "medium"
persona = "Review diffs."
""".strip(),
        encoding="utf-8",
    )


def _write_codex_contract(codex_home: Path) -> None:
    agents_dir = codex_home / "agents"
    agents_dir.mkdir(parents=True)
    (agents_dir / "sample.toml").write_text(
        '''
name = "sample"
description = "Sample agent"
model = "gpt-5.5"
model_reasoning_effort = "medium"
developer_instructions = """Act as sample."""
'''.strip(),
        encoding="utf-8",
    )


def test_materialization_plan_uses_enabled_agents_by_default(tmp_path: Path) -> None:
    codex_home = tmp_path / "codex-home"
    _write_codex_contract(codex_home)
    _write_agent_config(tmp_path)

    plan = build_codex_agent_materialization_plan(tmp_path, codex_home=codex_home)

    assert plan.supported is True
    assert plan.target == CodexAgentMaterializationTarget.PROJECT
    assert plan.capability.native_agent_toml_supported is True
    assert [file.agent_id for file in plan.files] == ["architect"]
    assert [file.materialized_agent_name for file in plan.files] == ["architect"]
    assert plan.files[0].target_path == str(
        tmp_path / ".codex" / "agents" / "architect.toml"
    )
    assert "Generated by agent-remote" in plan.files[0].content
    assert 'name = "architect"' in plan.files[0].content
    assert "Design typed boundaries." in plan.files[0].content
    assert "reviewer" not in plan.files[0].content


def test_materialization_plan_can_include_disabled_for_audit(tmp_path: Path) -> None:
    codex_home = tmp_path / "codex-home"
    _write_codex_contract(codex_home)
    _write_agent_config(tmp_path)

    plan = build_codex_agent_materialization_plan(
        tmp_path,
        codex_home=codex_home,
        include_disabled=True,
    )

    assert [file.agent_id for file in plan.files] == ["architect", "reviewer"]


def test_materialization_plan_can_target_global_namespace(tmp_path: Path) -> None:
    codex_home = tmp_path / "codex-home"
    _write_codex_contract(codex_home)
    _write_agent_config(tmp_path)

    plan = build_codex_agent_materialization_plan(
        tmp_path,
        codex_home=codex_home,
        target=CodexAgentMaterializationTarget.GLOBAL,
        namespace="sample-project",
    )

    assert plan.target == CodexAgentMaterializationTarget.GLOBAL
    assert plan.files[0].agent_id == "architect"
    assert plan.files[0].materialized_agent_name == "sample-project-architect"
    assert plan.files[0].target_path == str(
        codex_home / "agents" / "sample-project-architect.toml"
    )
    assert 'name = "sample-project-architect"' in plan.files[0].content


def test_materialization_plan_degrades_when_contract_is_unknown(tmp_path: Path) -> None:
    _write_agent_config(tmp_path)

    plan = build_codex_agent_materialization_plan(
        tmp_path,
        codex_home=tmp_path / "missing-codex-home",
    )

    assert plan.supported is False
    assert plan.files == ()
    assert "No Codex native agent TOML contract" in plan.warnings[0]
