from hashlib import sha256
from pathlib import Path

from omx_remote.runtime.agents.agent_config_loader import load_agent_config
from omx_remote.runtime.agents.codex_agent_capabilities import (
    detect_codex_agent_capabilities,
)
from omx_remote.schemas.agents.agent_config_schemas import AgentConfig, AgentConfigSet
from omx_remote.schemas.agents.codex_agent_materialization_schemas import (
    CodexAgentCapabilitySnapshot,
    CodexAgentMaterializationFile,
    CodexAgentMaterializationPlan,
)

GENERATED_HEADER = "Generated by agent-remote from .agent-remote.toml. Do not edit manually."


def _target_path(cwd: str | Path, agent_id: str) -> Path:
    """Build the project-local Codex agent target path.

    Args:
        cwd [str | Path]: Repository root.
        agent_id [str]: Agent id.

    Returns:
        Path: Target generated TOML path.
    """
    target: Path = Path(cwd).resolve() / ".codex" / "agents" / f"{agent_id}.toml"
    return target


def _toml_string(value: str) -> str:
    """Render a minimal TOML basic string.

    Args:
        value [str]: Value to render.

    Returns:
        str: TOML string literal.
    """
    escaped_value: str = value.replace("\\", "\\\\").replace('"', '\\"')
    rendered: str = f'"{escaped_value}"'
    return rendered


def _toml_multiline(value: str) -> str:
    """Render a minimal TOML multiline basic string.

    Args:
        value [str]: Value to render.

    Returns:
        str: TOML multiline string literal.
    """
    escaped_value: str = value.replace('"""', '\\"\\"\\"')
    rendered: str = f'"""{escaped_value}"""'
    return rendered


def _developer_instructions(agent: AgentConfig) -> str:
    """Render developer instructions from agent config.

    Args:
        agent [AgentConfig]: Source agent config.

    Returns:
        str: Developer instructions content.
    """
    routing_hint_text: str = ", ".join(agent.routing_hints)
    if routing_hint_text:
        instructions = (
            f"<role>{agent.role}</role>\n"
            f"<persona>{agent.persona}</persona>\n"
            f"<routing_hints>{routing_hint_text}</routing_hints>"
        )
        return instructions

    instructions = f"<role>{agent.role}</role>\n<persona>{agent.persona}</persona>"
    return instructions


def render_codex_agent_toml(agent: AgentConfig) -> str:
    """Render one Codex-native agent TOML file.

    Args:
        agent [AgentConfig]: Source agent config.

    Returns:
        str: Generated TOML content.
    """
    content = "\n".join(
        (
            f"# {GENERATED_HEADER}",
            f"name = {_toml_string(agent.id)}",
            f"description = {_toml_string(agent.role)}",
            f"model = {_toml_string(agent.model)}",
            f"model_reasoning_effort = {_toml_string(agent.effort)}",
            f"developer_instructions = {_toml_multiline(_developer_instructions(agent))}",
            "",
        )
    )
    return content


def _planned_file(cwd: str | Path, agent: AgentConfig) -> CodexAgentMaterializationFile:
    """Build one planned generated file.

    Args:
        cwd [str | Path]: Repository root.
        agent [AgentConfig]: Source agent config.

    Returns:
        CodexAgentMaterializationFile: Planned file.
    """
    content: str = render_codex_agent_toml(agent)
    digest: str = sha256(content.encode("utf-8")).hexdigest()
    planned_file = CodexAgentMaterializationFile(
        agent_id=agent.id,
        target_path=str(_target_path(cwd, agent.id)),
        content_sha256=digest,
        content=content,
    )
    return planned_file


def build_codex_agent_materialization_plan(
    cwd: str | Path,
    codex_home: str | Path | None = None,
    include_disabled: bool = False,
) -> CodexAgentMaterializationPlan:
    """Build a deterministic Codex agent materialization plan.

    Args:
        cwd [str | Path]: Repository root.
        codex_home [str | Path | None]: Optional Codex home used for contract detection.
        include_disabled [bool]: Whether disabled agents should appear in the plan.

    Returns:
        CodexAgentMaterializationPlan: Materialization plan.
    """
    config: AgentConfigSet = load_agent_config(cwd=cwd)
    capability: CodexAgentCapabilitySnapshot = detect_codex_agent_capabilities(
        codex_home=codex_home
    )
    if include_disabled:
        selected_agents: tuple[AgentConfig, ...] = config.agents
    else:
        selected_agents = config.enabled_agents

    if capability.native_agent_toml_supported:
        files: tuple[CodexAgentMaterializationFile, ...] = tuple(
            _planned_file(cwd, agent)
            for agent in selected_agents
            if agent.provider == "codex"
        )
    else:
        files = ()

    warnings: tuple[str, ...] = (*config.warnings, *capability.warnings)
    plan = CodexAgentMaterializationPlan(
        supported=capability.native_agent_toml_supported,
        capability=capability,
        source_config_path=config.config_path,
        files=files,
        warnings=warnings,
    )
    return plan
