import re
from hashlib import sha256
from pathlib import Path

from omx_remote.runtime.agents.agent_config_loader import load_agent_config
from omx_remote.runtime.agents.codex_agent_capabilities import (
    detect_codex_agent_capabilities,
)
from omx_remote.schemas.agents.agent_config_schemas import (
    AgentConfig,
    AgentConfigSet,
    AgentProvider,
)
from omx_remote.schemas.agents.codex_agent_materialization_schemas import (
    CodexAgentCapabilitySnapshot,
    CodexAgentMaterializationFile,
    CodexAgentMaterializationPlan,
    CodexAgentMaterializationTarget,
)
from omx_remote.shared.utils.toml_rendering import toml_multiline_string, toml_string

GENERATED_HEADER = (
    "Generated by comx-agent from .comx-agent.toml. Do not edit manually."
)


def _safe_namespace(value: str) -> str:
    """Normalize a value into a Codex-agent-name-safe namespace.

    Args:
        value [str]: Raw namespace candidate.

    Returns:
        str: Safe namespace segment.
    """
    normalized: str = re.sub(r"[^a-z0-9_-]+", "-", value.lower()).strip("-_")
    if not normalized:
        fallback_namespace = "project"
        return fallback_namespace
    if not normalized[0].isalnum():
        normalized = f"project-{normalized}"
    safe_namespace: str = normalized[:64].strip("-_") or "project"
    return safe_namespace


def _default_namespace(cwd: str | Path) -> str:
    """Build the default global-materialization namespace from the repo directory.

    Args:
        cwd [str | Path]: Repository root.

    Returns:
        str: Safe default namespace.
    """
    namespace: str = _safe_namespace(Path(cwd).resolve().name)
    return namespace


def _materialized_agent_name(
    agent_id: str,
    target: CodexAgentMaterializationTarget,
    namespace: str,
) -> str:
    """Build the Codex-visible agent name for a materialization target.

    Args:
        agent_id [str]: Agent id.
        target [CodexAgentMaterializationTarget]: Materialization target.
        namespace [str]: Safe global namespace.

    Returns:
        str: Codex-visible agent name.
    """
    if target == CodexAgentMaterializationTarget.GLOBAL:
        materialized_name = f"{namespace}-{agent_id}"
        return materialized_name

    materialized_name = agent_id
    return materialized_name


def _target_path(
    cwd: str | Path,
    codex_home: str | Path,
    target: CodexAgentMaterializationTarget,
    materialized_agent_name: str,
) -> Path:
    """Build the Codex agent target path.

    Args:
        cwd [str | Path]: Repository root.
        codex_home [str | Path]: Codex home path.
        target [CodexAgentMaterializationTarget]: Materialization target.
        materialized_agent_name [str]: Codex-visible generated agent name.

    Returns:
        Path: Target generated TOML path.
    """
    if target == CodexAgentMaterializationTarget.GLOBAL:
        agents_root: Path = Path(codex_home).resolve() / "agents"
    else:
        agents_root = Path(cwd).resolve() / ".codex" / "agents"

    target_path: Path = (agents_root / f"{materialized_agent_name}.toml").resolve()
    if target_path.parent != agents_root:
        raise ValueError(
            f"agent name is not safe for materialization: {materialized_agent_name}"
        )
    return target_path


def _developer_instructions(agent: AgentConfig) -> str:
    """Render developer instructions from agent config.

    Args:
        agent [AgentConfig]: Source agent config.

    Returns:
        str: Developer instructions content.
    """
    routing_hint_text: str = ", ".join(agent.routing_hints)
    if routing_hint_text:
        instructions = (
            f"<role>{agent.role}</role>\n"
            f"<persona>{agent.persona}</persona>\n"
            f"<routing_hints>{routing_hint_text}</routing_hints>"
        )
        return instructions

    instructions = f"<role>{agent.role}</role>\n<persona>{agent.persona}</persona>"
    return instructions


def render_codex_agent_toml(
    agent: AgentConfig,
    materialized_agent_name: str | None = None,
) -> str:
    """Render one Codex-native agent TOML file.

    Args:
        agent [AgentConfig]: Source agent config.
        materialized_agent_name [str | None]: Optional Codex-visible agent name.

    Returns:
        str: Generated TOML content.
    """
    agent_name: str = (
        agent.id if materialized_agent_name is None else materialized_agent_name
    )
    content = "\n".join(
        (
            f"# {GENERATED_HEADER}",
            f"name = {toml_string(agent_name)}",
            f"description = {toml_string(agent.role)}",
            f"model = {toml_string(agent.model)}",
            f"model_reasoning_effort = {toml_string(agent.effort)}",
            f"developer_instructions = {toml_multiline_string(_developer_instructions(agent))}",
            "",
        )
    )
    return content


def _planned_file(
    cwd: str | Path,
    codex_home: str | Path,
    agent: AgentConfig,
    target: CodexAgentMaterializationTarget,
    namespace: str,
) -> CodexAgentMaterializationFile:
    """Build one planned generated file.

    Args:
        cwd [str | Path]: Repository root.
        codex_home [str | Path]: Codex home path.
        agent [AgentConfig]: Source agent config.
        target [CodexAgentMaterializationTarget]: Materialization target.
        namespace [str]: Safe global namespace.

    Returns:
        CodexAgentMaterializationFile: Planned file.
    """
    materialized_agent_name: str = _materialized_agent_name(
        agent.id,
        target,
        namespace,
    )
    content: str = render_codex_agent_toml(agent, materialized_agent_name)
    digest: str = sha256(content.encode("utf-8")).hexdigest()
    planned_file = CodexAgentMaterializationFile(
        agent_id=agent.id,
        materialized_agent_name=materialized_agent_name,
        target_path=str(_target_path(cwd, codex_home, target, materialized_agent_name)),
        content_sha256=digest,
        content=content,
    )
    return planned_file


def build_codex_agent_materialization_plan(
    cwd: str | Path,
    codex_home: str | Path | None = None,
    include_disabled: bool = False,
    target: CodexAgentMaterializationTarget = CodexAgentMaterializationTarget.PROJECT,
    namespace: str | None = None,
) -> CodexAgentMaterializationPlan:
    """Build a deterministic Codex agent materialization plan.

    Args:
        cwd [str | Path]: Repository root.
        codex_home [str | Path | None]: Optional Codex home used for contract detection.
        include_disabled [bool]: Whether disabled agents should appear in the plan.
        target [CodexAgentMaterializationTarget]: Materialization target.
        namespace [str | None]: Optional global target namespace.

    Returns:
        CodexAgentMaterializationPlan: Materialization plan.
    """
    config: AgentConfigSet = load_agent_config(cwd=cwd)
    capability: CodexAgentCapabilitySnapshot = detect_codex_agent_capabilities(
        codex_home=codex_home
    )
    resolved_namespace: str = (
        _default_namespace(cwd) if namespace is None else _safe_namespace(namespace)
    )
    if include_disabled:
        selected_agents: tuple[AgentConfig, ...] = config.agents
    else:
        selected_agents = config.enabled_agents

    if capability.native_agent_toml_supported:
        files: tuple[CodexAgentMaterializationFile, ...] = tuple(
            _planned_file(
                cwd,
                capability.codex_home,
                agent,
                target,
                resolved_namespace,
            )
            for agent in selected_agents
            if agent.provider == AgentProvider.CODEX
        )
    else:
        files = ()

    warnings: tuple[str, ...] = (*config.warnings, *capability.warnings)
    plan = CodexAgentMaterializationPlan(
        supported=capability.native_agent_toml_supported,
        target=target,
        capability=capability,
        source_config_path=config.config_path,
        files=files,
        warnings=warnings,
    )
    return plan
